// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqgnoxybutzyagmdektw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xZ25veHlidXR6eWFnbWRla3R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3MTUzNjAsImV4cCI6MjA4NzI5MTM2MH0.GVe3fD1ZTKHswe459e__iuherxZ8pQX9Ck1oGKNMn9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});